### ISSUE TITLE
Handle garbage collection

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/DNSAuth#15]
We should add an option in [dnsauth.toml](https://github.com/Packet-Clearing-House/DNSAuth/blob/master/DNSAuth/dnsauth.toml) where after DNSAuth ingests the log files you can:
* do nothing (current feature)
* move to specified directory 
* delete 

Running an external cron script that deletes them is a hassle and may be too aggressive and delete them before they're indexed.

**Comment by mrjones-plip** [comment]
fixed in #25
